# Generated by Django 6.1 on 2026-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_codingquestion_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='expected_answer',
            field=models.TextField(blank=True),
        ),
    ]
