# Generated by Django 6.1 on 2026-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_codingattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='interview_rounds',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='preparation_tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
