# Generated by Django 6.1 on 2026-09-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_company_eligibility_company_interview_rounds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('dbms', 'DBMS'), ('oops', 'OOP'), ('os', 'Operating Systems'), ('cn', 'Computer Networks'), ('general', 'General Technical')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
